CREATE DATABASE DB_TOYS_COMMERCE;

USE DB_TOYS_COMMERCE;

CREATE TABLE TB_ESTOQUE(
ID BIGINT AUTO_INCREMENT,
PRODUTO VARCHAR (255) NOT NULL,
QUANTIDADE INT (255) NOT NULL,
FORNECEDOR VARCHAR (255) NOT NULL,
PUBLICO VARCHAR (255) NOT NULL,
PRECO DOUBLE,
PRIMARY KEY(ID)
);

SELECT * FROM TB_ESTOQUE;

INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("CARRINHO HOT WHEELS", 30, "HI HAPPY", "JOVEM", 15.00);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("BONECA BARBIE", 100, "ESTRELA", "JOVEM", 80.00);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("MESINHA DIDATICA", 200, "AMAZON","BEBE", 70.00);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("BANCO IMOBILIARIO", 400, "ATM", "ADOLESCENTE", 164.00);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("SKATE", 300, "CB","ADULTO", 223.90);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("BONECA REBORN", 189, "MUNDO BABY REBORN", "ADOLESCENTE", 567.00);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("PELUCIA GENGAR", 120, "DUPARI", "CRIANÇA", 84.90);
INSERT INTO TB_ESTOQUE(PRODUTO,QUANTIDADE,FORNECEDOR,PUBLICO,PRECO)
VALUES ("LEGO STAR WARS", 700, "DULAR", "JOVEM", 1.600); 

ALTER TABLE TB_ESTOQUE MODIFY PRECO DECIMAL (6,2);

UPDATE TB_ESTOQUE SET PRECO = 900 WHERE ID = 7;

SELECT * FROM TB_ESTOQUE WHERE PRECO < 500;

SELECT * FROM TB_ESTOQUE WHERE PRECO > 500;