CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSE(
ID INT AUTO_INCREMENT,
NOME_CLASSE VARCHAR (244) NOT NULL,
HABILIDADE VARCHAR (244) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO TB_CLASSE (NOME_CLASSE, HABILIDADE)
VALUES ("ESPADACHIM","CORTE RÁPIDO");
INSERT INTO TB_CLASSE (NOME_CLASSE, HABILIDADE)
VALUES("MAGO", "NÉVOA OBSCURA");
INSERT INTO TB_CLASSE (NOME_CLASSE, HABILIDADE)
VALUES("LADINO", "PASSOS SILENCIOSOS");
INSERT INTO TB_CLASSE (NOME_CLASSE, HABILIDADE)
VALUES ("GUERREIRO","O DUELISTA");
INSERT INTO TB_CLASSE (NOME_CLASSE, HABILIDADE)
VALUES ("CLÉRIGO", "BENÇÃO DIVINA");

SELECT * FROM TB_CLASSE;


CREATE TABLE TB_PERSONAGEM(
ID INT AUTO_INCREMENT,
NOME_PERSONAGEM VARCHAR (244) NOT NULL,
RACA VARCHAR (244) NOT NULL,
ARMA_PRINCIPAL VARCHAR (244) NOT NULL,
DEFESA INT NOT NULL,
ATAQUE decimal NOT NULL,
CLASSE INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(CLASSE) REFERENCES TB_CLASSE(ID)
);

INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("HELENA", "TIEFLING", "CLAVA", 245, 1.000, 5);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("AKYN", "HUMANO", "ARCO CURTO", 986, 5.000, 3);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("CESAR", "DRACONATO", "ESPADA", 999, 2.000, 4);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("EMMA", "ELFO", "CAJADO MAGICO",300 ,1.100 , 2);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("GAZ", "MEIO ELFO", "KATANA",800 ,3.000 , 1);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("LIZA", "HALFLING", "VARINHA MAGICA",200 ,1.500 , 2);
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("SEONI", "ANÃO", "ESTILINGUE",87 ,2.500 ,3 );
INSERT INTO TB_PERSONAGEM(NOME_PERSONAGEM, RACA, ARMA_PRINCIPAL, DEFESA, ATAQUE, CLASSE)
VALUES ("JORAN", "ORC", "MARTELO",100 ,1.000 ,5 );

SELECT * FROM TB_PERSONAGEM;

ALTER TABLE TB_PERSONAGEM MODIFY ATAQUE DECIMAL (6,3);

SELECT * FROM TB_PERSONAGEM WHERE ATAQUE >2.000;

SELECT * FROM TB_PERSONAGEM WHERE DEFESA BETWEEN 100 AND 200;

SELECT * FROM TB_PERSONAGEM WHERE NOME_PERSONAGEM LIKE "%C%";

SELECT * FROM TB_PERSONAGEM INNER JOIN tb_classe ON CLASSE = TB_CLASSE.ID;

SELECT * FROM TB_PERSONAGEM INNER JOIN TB_CLASSE ON CLASSE = TB_CLASSE.id
WHERE TB_CLASSE.id = 2;



