CREATE DATABASE DB_RECURSOS_HUMANOS;

USE DB_RECURSOS_HUMANOS;

CREATE TABLE TB_COLABORADORES(
FUNCIONAL bigint auto_increment,
NOME VARCHAR (244) NOT NULL,
CPF VARCHAR (244) NOT NULL,
CARGO VARCHAR (244) NOT NULL,
SALARIO DOUBLE,
IDADE INT,
PRIMARY KEY(FUNCIONAL)
);

select * from TB_COLABORADORES;

INSERT INTO TB_COLABORADORES(NOME, CPF, CARGO, SALARIO, IDADE)
VALUES ("PEDRO", "783.743.920-02", "ESTAGIARIO", 2.400, 23);
INSERT INTO TB_COLABORADORES(NOME, CPF, CARGO, SALARIO, IDADE)
VALUES ("VIVIANE", "454.981.254-07", "DESENVOLVEDORA BACK-END", 5.800, 30);
INSERT INTO TB_COLABORADORES(NOME, CPF, CARGO, SALARIO, IDADE)
VALUES ("ALANA", "865.262.981-56", "RECEPCIONISTA", 2.000, 37);
INSERT INTO TB_COLABORADORES(NOME, CPF, CARGO, SALARIO, IDADE)
VALUES ("IRIS", "233.986.213-12", "GERENTE", 7.000, 45);
INSERT INTO TB_COLABORADORES(NOME, CPF, CARGO, SALARIO, IDADE)
VALUES ("CAMILLE", "923.143.982-87", "SUPERVISOR", 3.558, 20);

ALTER TABLE TB_COLABORADORES MODIFY SALARIO DECIMAL (6,3);

DELETE FROM TB_COLABORADORES WHERE FUNCIONAL = 2;

UPDATE TB_COLABORADORES SET SALARIO = 1.500 WHERE FUNCIONAL = 3;

SELECT * FROM TB_COLABORADORES WHERE SALARIO < 2.000;

SELECT * FROM TB_COLABORADORES WHERE SALARIO > 2.000;
