CREATE DATABASE REGISTRO_SETIMA_SERIE;

USE REGISTRO_SETIMA_SERIE;

CREATE TABLE TB_ALUNOS_DE_RECUPERACAO(
ID BIGINT AUTO_INCREMENT,
ALUNO VARCHAR (255) NOT NULL,
TURMA VARCHAR (255) NOT NULL,
PROFESSOR VARCHAR (255) NOT NULL,
MATERIA VARCHAR (255) NOT NULL,
NOTA DOUBLE, 
PRIMARY KEY(ID)
);

SELECT * FROM TB_ALUNOS_DE_RECUPERACAO;

INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("RAFAEL", "7°ANO B", "ELIZABETH", "QUIMICA", 4.0);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("DAISY", "7°ANO B", "CAMILLE", "FISICA", 3.14);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("STEPHANY", "7°ANO B", "ROBERTO", "LINGUA PORTUGUESA", 2.0);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("ALEXANDRE", "7°ANO A", "ANDERSON", "MATEMATICA", 3.0);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("ENZO", "7°ANO A", "ELIZABETH", "QUIMICA", 5.30);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("MARCELA", "7°ANO A", "ANA", "HISTORIA", 4.00);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("JAQUELINE", "7°ANO C", "ROBERTO", "LINGUA PORTUGUESA", 3.00);
INSERT INTO TB_ALUNOS_DE_RECUPERACAO(ALUNO,TURMA,PROFESSOR,MATERIA,NOTA)
VALUES ("POLIANA", "7°ANO C", "ELIZABETH", "QUIMICA", 1.00);

ALTER TABLE TB_ALUNOS_DE_RECUPERACAO MODIFY NOTA DECIMAL (6,2);

SELECT * FROM TB_ALUNOS_DE_RECUPERACAO WHERE NOTA < 7.0;

SELECT * FROM TB_ALUNOS_DE_RECUPERACAO WHERE NOTA > 7.0;

UPDATE TB_ALUNOS_DE_RECUPERACAO SET NOTA = 9.0 WHERE ID = 3;

UPDATE TB_ALUNOS_DE_RECUPERACAO SET NOTA = 10 WHERE ID = 1;

UPDATE TB_ALUNOS_DE_RECUPERACAO SET NOTA = 8 WHERE ID = 7;